# Configuraci칩n temporal m치s permisiva para permitir compilaci칩n
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "**/generated_plugin_registrant.dart"

linter:
  rules:
    # Deshabilitamos temporalmente las reglas m치s estrictas
    always_use_package_imports: false
    prefer_relative_imports: false
    avoid_dynamic_calls: false

    require_trailing_commas: false
    prefer_const_constructors: false
    unnecessary_await_in_return: false
    sort_constructors_first: false
    use_super_parameters: false
    avoid_annotating_with_dynamic: false
    omit_local_variable_types: false
    prefer_final_locals: false
    prefer_final_fields: false
    unnecessary_breaks: false
    unnecessary_lambdas: false
    avoid_redundant_argument_values: false
    prefer_int_literals: false
    use_raw_strings: false

    use_decorated_box: false
    use_colored_box: false
    use_named_constants: false
    unnecessary_to_list_in_spreads: false
    eol_at_end_of_file: false
    directives_ordering: false
    sort_pub_dependencies: false
    always_put_required_named_parameters_first: false
    sort_unnamed_constructors_first: false
    unnecessary_brace_in_string_interps: false
    use_build_context_synchronously: false
    noop_primitive_operations: false
    unnecessary_null_checks: false
    prefer_single_quotes: false
