name: rouwhite
description: "A new Flutter project."
publish_to: "none"

version: 1.0.6+7

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI and Icons
  cupertino_icons: ^1.0.8
  flutter_vector_icons: ^2.0.0
  lottie: ^3.2.0
  flutter_animate: ^4.5.2

  # Maps and Location - Fixed stable versions for CI/CD
  flutter_map: 8.1.0 # Versión fija sin problemas de const
  latlong2: 0.9.1 # Compatible con flutter_map 8.1.0
  flutter_polyline_points: 2.0.0 # Versión fija más estable
  geolocator: 9.0.2 # Versión fija estable sin problemas de CI

  # State Management
  provider: ^6.1.5

  # Data and Storage
  shared_preferences: ^2.5.3
  equatable: ^2.0.7

  # Network and API
  dio: ^5.9.0
  internet_connection_checker: ^1.0.0+1
  network_info_plus: ^5.0.0
  geocoding: ^4.0.0

  # Utilities
  dartz: ^0.10.1
  intl: ^0.20.2
  url_launcher: ^6.3.1
  package_info_plus: ^8.0.3

  # Voice and Audio
  flutter_tts: ^4.2.3
  permission_handler: ^12.0.1
  file_picker: ^8.0.3

  # Development and Debugging
  logger: ^2.0.2

  # WebView for HTML integration
  webview_flutter: ^4.10.0

  # Firebase
  firebase_core: ^3.15.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # ✅ Compatible con SDK 3.2.x
  flutter_lints: ^3.0.0

  # Testing
  mockito: ^5.4.4
  build_runner: ^2.4.7
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/animaciones/bus.json

# Dependency overrides for CI/CD stability - Fixed versions
dependency_overrides:
  # Stable versions that work in CI environments
  geolocator_android: 4.4.0 # Versión más estable para CI
  geolocator_platform_interface: 4.0.6 # Compatible con geolocator 9.0.2
  flutter_map: 8.1.0 # Versión fija
  latlong2: 0.9.1 # Versión fija compatible
  geolocator: 9.0.2 # Versión fija
  # Agregar overrides adicionales para resolver conflictos
  geolocator_web: 2.1.6 # Compatible con geolocator 9.0.2
  geolocator_windows: 0.1.1 # Compatible con geolocator 9.0.2
